INSERT INTO product (name, description, scent, size, price, stock_quantity) VALUES
('Honeysuckle Jasmine - Large', 'Honeysuckle Jasmine is a sweet and floral fragrance blending the aromatic notes of honeysuckle and jasmine.', 'Honeysuckle Jasmine', 'Large', 30.00, 20),
('Honeysuckle Jasmine - Medium', 'Honeysuckle Jasmine is a sweet and floral fragrance blending the aromatic notes of honeysuckle and jasmine.', 'Honeysuckle Jasmine', 'Medium', 24.00, 20),
('Honeysuckle Jasmine - Small', 'Honeysuckle Jasmine is a sweet and floral fragrance blending the aromatic notes of honeysuckle and jasmine.', 'Honeysuckle Jasmine', 'Small', 12.00, 20),
('Watermelon Lemonade - Large', 'Watermelon Lemonade is a refreshing scent combining the juicy essence of watermelon with zesty lemon notes.', 'Watermelon Lemonade', 'Large', 30.00, 20),
('Watermelon Lemonade - Medium', 'Watermelon Lemonade is a refreshing scent combining the juicy essence of watermelon with zesty lemon notes.', 'Watermelon Lemonade', 'Medium', 24.00, 20),
('Watermelon Lemonade - Small', 'Watermelon Lemonade is a refreshing scent combining the juicy essence of watermelon with zesty lemon notes.', 'Watermelon Lemonade', 'Small', 12.00, 20),
('Vanilla - Large', 'Vanilla is a warm and sweet scent with a rich, comforting aroma.', 'Vanilla', 'Large', 30.00, 20),
('Vanilla - Medium', 'Vanilla is a warm and sweet scent with a rich, comforting aroma.', 'Vanilla', 'Medium', 24.00, 20),
('Vanilla - Small', 'Vanilla is a warm and sweet scent with a rich, comforting aroma.', 'Vanilla', 'Small', 12.00, 20),
('Fruit Slices - Large', 'Fruit Slices is a vibrant and fruity scent reminiscent of freshly sliced fruits.', 'Fruit Slices', 'Large', 30.00, 20),
('Fruit Slices - Medium', 'Fruit Slices is a vibrant and fruity scent reminiscent of freshly sliced fruits.', 'Fruit Slices', 'Medium', 24.00, 20),
('Fruit Slices - Small', 'Fruit Slices is a vibrant and fruity scent reminiscent of freshly sliced fruits.', 'Fruit Slices', 'Small', 12.00, 20),
('Lavender - Large', 'Lavender is a calming and aromatic scent known for its soothing properties.', 'Lavender', 'Large', 30.00, 20),
('Lavender - Medium', 'Lavender is a calming and aromatic scent known for its soothing properties.', 'Lavender', 'Medium', 24.00, 20),
('Lavender - Small', 'Lavender is a calming and aromatic scent known for its soothing properties.', 'Lavender', 'Small', 12.00, 20),
('Sunwashed Linen - Large', 'Sunwashed Linen evokes the fresh and crisp fragrance of sun-dried fabrics.', 'Sunwashed Linen', 'Large', 30.00, 20),
('Sunwashed Linen - Medium', 'Sunwashed Linen evokes the fresh and crisp fragrance of sun-dried fabrics.', 'Sunwashed Linen', 'Medium', 24.00, 20),
('Sunwashed Linen - Small', 'Sunwashed Linen evokes the fresh and crisp fragrance of sun-dried fabrics.', 'Sunwashed Linen', 'Small', 12.00, 20),
('Green Tea - Large', 'Green Tea offers a calming and refreshing aroma with subtle herbal notes.', 'Green Tea', 'Large', 30.00, 20),
('Green Tea - Medium', 'Green Tea offers a calming and refreshing aroma with subtle herbal notes.', 'Green Tea', 'Medium', 24.00, 20),
('Green Tea - Small', 'Green Tea offers a calming and refreshing aroma with subtle herbal notes.', 'Green Tea', 'Small', 12.00, 20),
('Ocean Waves - Large', 'Ocean Waves captures the invigorating freshness of sea breezes and the calming essence of the ocean.', 'Ocean Waves', 'Large', 30.00, 20),
('Ocean Waves - Medium', 'Ocean Waves captures the invigorating freshness of sea breezes and the calming essence of the ocean.', 'Ocean Waves', 'Medium', 24.00, 20),
('Ocean Waves - Small', 'Ocean Waves captures the invigorating freshness of sea breezes and the calming essence of the ocean.', 'Ocean Waves', 'Small', 12.00, 20);
